require('plugins')
require('keymaps')
require('_whichkey')
require('_treesitter')
require('_cmp')
require('options')
require('vimslime')
require('_lspconfig')
require('_lualine')
require('_vimtex')
require('_telescope')
require('_aerial')
require('_nvimtree')
require('_noice')

vim.filetype.add({ extension = { mma = 'wolfram' } })
vim.filetype.add({ extension = { hip = "hip" } })
